import "./globals.css";
import { Montserrat } from "next/font/google";

export const metadata = {
  title: "Genfar Quien Quiere Ser Millonario",
  description: "Generated by create next app",
};

const mont = Montserrat({
  weight: ['400', '700'], // Puedes especificar pesos
  subsets: ['latin'],     // Asegúrate de incluir los subsets necesarios
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${mont.className}`}>{children}</body>
    </html>
  );
}
